onCall/core/urls.py
from django.urls import path
from . import views
from .views import HomePageView,EspecialidadListView,EspecialidadDetail, GuardiaDetail, TablaDetail, RegionesListView,GuardiaRegionDetail,SubEspecialidadDetail,GuardiasEspecialistasListView,GuardiasEspecialistasUpdateView, GuardiasEspecialistasDeleteView,GuardiaSemanalCreate



app_name= 'core'
urlpatterns = [
	path('', HomePageView.as_view(), name="home"),
	path('especialidades/', EspecialidadListView.as_view(), name="especialidades_list"),
	path('regiones/', RegionesListView.as_view(), name="regiones_list"),
	path('region/<int:pk>/', GuardiaRegionDetail.as_view(), name="guardia_region_detail"),


	path('especialidad/<int:pk>/', EspecialidadDetail.as_view(), name="especialidad_detail"),
	path('subespecialidad/<int:pk>/', SubEspecialidadDetail.as_view(), name="subespecialidad_detail"),
	path('guardia/<int:pk>/', GuardiaDetail.as_view(), name="guardia_detail"),
	path('tabla/<int:pk>/', TablaDetail.as_view(), name="tabla_detail"),


	path('create_guardia_semanal/', GuardiaSemanalCreate.as_view(), name='guardiaSemanal_create'),

	path('guardias/especialistas/', GuardiasEspecialistasListView.as_view(), name="guardias_especialistas_list"),
	path('guardias/especialistas/update/<int:pk>/', GuardiasEspecialistasUpdateView.as_view(), name="guardias_especialistas_update"),
	path('guardias/especialistas/delete/<int:pk>/', GuardiasEspecialistasDeleteView.as_view(), name="guardias_especialistas_delete"),

	path('guardias/calendario/', views.calendario, name="calendario"),


]

onCall/onCall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from registration import views

urlpatterns = [
    path('', include('core.urls')),
    path("logout", views.logout_request, name= "logout"),
    path('accounts/', include('django.contrib.auth.urls')),


    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

onCall/core/models.py
from django.db import models
from colorfield.fields import ColorField
from django.core.exceptions import ValidationError
from django.utils import  timezone
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import pre_save, m2m_changed
from .task import telegram_api
now = timezone.now

# Create your models here.

def numeros_validos(value):
    value = str(value)
    if len(value) != 11:
        raise ValidationError("La longitud no corresponde con la establecidad de 11 digitos...")

    elif value[0] != '5':
        raise ValidationError("No comienza con 5")

    elif value[1] != '6':
        raise ValidationError("No contiene el  6 como segundo digito")




NIVEL = (
    (1, 'Especialista'),
    (2, 'Supervisor'),
    (3, 'Jefe de área'),
    (4, 'Gerente de área'),
    (5, 'Gerente'),
)


class Especialidad(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Nombre de la Especialidad", blank=True, null=True)


    class Meta:
        verbose_name = "Especialidad"
        verbose_name_plural = "Especialidades"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name"]

    def __str__(self):
        return self.name


class SubEspecialidad(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Nombre", blank=True, null=True)
    especialidad = models.ForeignKey(Especialidad, on_delete=models.CASCADE, related_name="get_especialidad",
                                verbose_name="Especialidad")


    class Meta:
        verbose_name = "Sub-Especialidad"
        verbose_name_plural = "Sub-Especialidades"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name"]

    def __str__(self):
        return self.name




class Zona(models.Model):
    name = models.CharField(max_length=200, verbose_name="Zona", blank=True, null=True)


    class Meta:
        verbose_name = "Zona"
        verbose_name_plural = "Zonas"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name"]

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nombre de la region", blank=True, null=True)
    zona = models.ForeignKey(Zona, on_delete=models.CASCADE, related_name="get_zona",
                                verbose_name="Zona", blank=True, null=True)



    class Meta:
        verbose_name = "Region"
        verbose_name_plural = "Regiones"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name"]

    def __str__(self):
        return self.name


class Guardia(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Nombre", blank=True, null=True)
    sub_especilidad = models.ForeignKey(SubEspecialidad, on_delete=models.CASCADE, related_name="get_sub_especilidad",
                                verbose_name="Sub-especilidad", blank=True, null=True)

    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name="get_region",
                                        verbose_name="Región", blank=True, null=True)
    color_fondo = ColorField(verbose_name="Color de fondo", blank=True, null=True, default='#FFFFFF')
    color_texto = ColorField(verbose_name="Color del texto", blank=True, null=True, default='#FFFFFF')



    class Meta:
        verbose_name = "Guardia"
        verbose_name_plural = "Guardias"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name"]

    def __str__(self):
        return self.name



class Profile(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nombre del Especialista", blank=True, null=True)
    email = models.EmailField(max_length=100, verbose_name="Email del Especialista", blank=True, null=True)
    nivel = models.IntegerField(choices=NIVEL, verbose_name="Nivel de Escalamiento", blank=True, null=True)
    phone_guardia = models.CharField(max_length=20, verbose_name="Teléfono de Guardia", blank=True, null=True, validators=[numeros_validos], help_text='Debe contener 11 digitos y empezar con 56')
    phone_asignado = models.CharField(max_length=20, verbose_name="Teléfono Asignado", blank=True, null=True, validators=[numeros_validos], help_text='Debe contener 11 digitos y empezar con 56')
    phone_otro = models.CharField(max_length=20, verbose_name="Teléfono de Otra Compañia", blank=True, null=True, validators=[numeros_validos], help_text='Debe contener 11 digitos y empezar con 56')
    fijo_oficina = models.CharField(max_length=20, verbose_name="Fijo Oficina", blank=True, null=True)
    fijo_casa = models.CharField(max_length=20, verbose_name="Fijo Casa", blank=True, null=True, validators=[numeros_validos], help_text='Debe contener 11 digitos y empezar con 56')
    guardia = models.ManyToManyField(Guardia, related_name="get_guardias", verbose_name="Guardia", blank=True)


    class Meta:
        verbose_name = "Especialista"
        verbose_name_plural = "Especialistas"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["nivel"]

    def __str__(self):
        return self.name



class GuardiaEspecialista(models.Model):
    name = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="get_especialistas",
                              verbose_name="Seleccione el especialista", blank=True, null=True)
    activo = models.BooleanField(verbose_name="Trae la Guardia", blank=True, null=True, default=True)
    fecha_inicio = models.DateTimeField(verbose_name="Fecha Inicio", blank=True, null=True,  default=now)
    fecha_fin = models.DateTimeField(verbose_name="Fecha Fin", blank=True, null=True,  default=now)
    guardia =  models.ManyToManyField(Guardia, related_name="get_guardiasespecialistas", verbose_name="Guardia", blank=True)



    class Meta:
        verbose_name = "Guardia por Especialista"
        verbose_name_plural = "Guardias por Especialistas"
        # Ordena de mas nuevo a mas antiguo
        ordering = ["name",]

    def __str__(self):
        return str(self.name.name)






"""
@receiver(pre_save, sender=Especialista)
def historico(sender,instance, **kwargs):
    try:
        old_instance = sender.objects.get(pk=instance.pk)
        if (old_instance.activo != instance.activo or old_instance.fecha_inicio != instance.fecha_inicio or old_instance.fecha_fin != instance.fecha_fin) and instance.activo ==True:
            guardias = Guardia.objects.filter(get_guardias=instance.pk)
            lista = []
            for guardia in guardias:
                lista.append(guardia.name)
            strA = "\n".join(lista)
            Historico.objects.create(name=old_instance.name, fecha_inicio= old_instance.fecha_inicio,fecha_fin=old_instance.fecha_fin, activo= old_instance.activo, guardia=strA)
            texto = f'Se notifica el siguiente cambio para la guardia de la {instance.zona}/{instance.region}:\n Acutalmente está de guardia {instance.name} con sus telefonos de contactos...'

            telegram_api(texto, '1663958489')

    except sender.DoesNotExist:
        pass



@receiver(m2m_changed, sender=Especialista.guardia.through)
def historico_m2m(sender,instance,action, **kwargs):
    try:
        if action =="pre_add":
            lista_pre = []
            for guardia in instance.guardia.all():
                lista_pre.append(guardia.name)
            str_pre = "\n".join(lista_pre)
            texto= f'Hubo un cambio en la guardia de {instance.name}:\nAntes tenia las siguientes guardias\n{str_pre}'
            telegram_api(texto, '1663958489')

        elif action=="post_add":
            lista_post = []
            for guardia in instance.guardia.all():
                lista_post.append(guardia.name)
            str_post = "\n".join(lista_post)
            texto = f'Ahora tiene las siguientes guardias:\n {str_post}'
            telegram_api(texto, '1663958489')
            Historico.objects.create(name=instance.name, fecha_inicio=instance.fecha_inicio,
                                     fecha_fin=instance.fecha_fin, activo=instance.activo,
                                     guardia=f'Guardias actualizadas:\n{str_post}')

    except sender.DoesNotExist:
        pass


"""

onCall/core/forms.py
from django import forms
from .models import GuardiaEspecialista, Guardia
from django.utils import  timezone
now = timezone.now








class GuardiaEspecialistaForm(forms.ModelForm):
    class Meta:
        model = GuardiaEspecialista
        fields = ['name', 'fecha_inicio','fecha_fin','guardia']
        widgets = {
            'name': forms.Select(
                attrs={'class': 'form-control mt-3',  'required': 'True', 'type':'text'}),
            'fecha_inicio': forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S', attrs={'class': 'form-control mt-3'}),
            'fecha_fin': forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S',
                                                attrs={'class': 'form-control mt-3'}),
            'guardia': forms.SelectMultiple(attrs={'class': 'form-control-file mt-3'}),
        }

        labels = {
            'fecha_inicio': 'Fecha de Inicio',
        }

onCall/core/templates/core/base.html
<!doctype html>
<html lang="es">
<head>  
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" type="#" href="#">
  {% load static %}
  <!-- ARCHIVOS CSS BOOTSTRAP 4 -->
  <link type="text/css" rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
  <!-- ARCHIVOS CSS PERSONALIZADOS -->
  <link type="text/css" rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    <!-- ICONOS BOOSTRAP -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">


  {% block css_extra %}{% endblock %}

    <title>{% block title %}{% endblock %}  | Inetum</title>
</head>
<body>

   
    <!-- INICIO DE LA BARRA DE NAVEGACION -->
    <nav class="navbar navbar-dark navbar-expand-md" style="background-color: #232d4b;">
      <div class="container">
        <a href="{% url 'core:home' %}" class="navbar-brand">
          <img src="{% static 'core/images/inetum.png' %}" alt="Logo del sitio" width="150">
        </a>
          {% if not  request.path == '/create_guardia_semanal/' %}
      <form class="d-flex ml-5 pl-5" role="search">{% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-primary ml-2" type="submit">Search</button>
      </form>
          {% endif %}


        {% if not request.user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link btn btn-outline-primary me-2">Login</a></li>
      </ul>
         {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item text-white mr-3 my-auto">Bienvenido {{user}}</li>

        <li class="nav-item"><a href="/logout" class="nav-link btn btn-outline-primary me-2" style="color:white;">Logout</a></li>
        {% if request.user.is_staff %}
         <li class="nav-item ml-2"><a href="{% url 'core:guardiaSemanal_create'  %}" class="nav-link btn btn-outline-primary me-2" style="color:white;">Carga</a></li>
         {% endif %}
      </ul>

         {% endif  %}
      </div>
    </nav>
    <!-- /FIN DE LA BARRA DE NAVEGACION -->

    {% include 'registration/includes/messages.html' %}
        {% if request.user.is_authenticated %}
         {% block content %}{% endblock %}
          {% endif %}
         {% block login %}{% endblock %}





 
<!-- ARCHIVOS BOOTSTRAP JAVASCRIPT -->
<script src="{% static 'core/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'core/js/popper.min.js' %}"></script>
<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
<script src="{% static 'core/js/jquery.chained.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/i18n/es.js"></script>
 {% block js_extra %}{% endblock %}

</body>
</html>

onCall/core/templates/core/calendario.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Calendario Ot Grtc{% endblock %}
{% load static %}
{% block css_extra %}
    <link rel="stylesheet" href="{% static 'core/lib/main.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.bootstrap4.min.css" rel="stylesheet" />

{% endblock %}
{% block content %}
       <div class="container">
           <div class="row">
               <div class="col-12">
                <form class="form-inline"  method ="GET">
                    {% csrf_token %}
                  <select class="custom-select my-3 mr-sm-2 col-10" id="id_guardia" name="guardia">
                     <option selected>Seleccione...</option>
                      {% for guardia in guardias %}
                    <option value="{{guardia.id}}">{{guardia.name}}</option>
                    {% endfor %}
                  </select>
                <button type="submit" class="btn btn-secondary ml-2 my-1 float-right ">Seleccionar</button>
            </form>
            </div>
          </div>
        </div>
    <div class="container my-3" id='calendar'></div>

{{ots_aprobadas}}

{% endblock  %}





{% block js_extra %}




<script type="text/javascript" src="{% static 'core/lib/main.js' %}"></script>
<script type="text/javascript" src="{% static 'core/lib/locales-all.js' %}"></script>


<script type="text/javascript">
    document.addEventListener('DOMContentLoaded',function(){
        var calendarUI = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarUI,{

       timeZone: 'local',
        initialView: 'dayGridMonth',
        headerToolbar: {
            left: 'prev next today',
            center: 'title',
            right: 'dayGridMonth timeGridWeek listWeek'
        },

            events:[
               {% for item in guardias_especialistas %}
                {
                    title:"{{item.name.name}}",
                    start:"{{item.fecha_inicio|date:'Y-m-d'}} {{item.fecha_inicio|time:'H:i'}}",
                    end:"{{item.fecha_fin|date:'Y-m-d'}} {{item.fecha_fin|time:'H:i'}}",
                    url:"{% url 'core:guardias_especialistas_update' item.id  %}",
                    backgroundColor:"{{guardia_color.color_fondo}}",
                    borderColor:"{{ot.color_borde}}",
                    textColor:"{{guardia_color.color_texto}}",
                },
                 {% endfor %}

            ]

        });
        calendar.render();
        calendar.setOption('locale','es');
    });



</script>

 <script>
  $(function(){
    $("#id_guardia").select2({
        allowCLear:true,
        languaje: "es",
         placeholder:"Seleccione una Guardia",
    });



    });
</script>
{% endblock  %}

onCall/core/templates/core/guardia_Semanal-ajax.html
{% extends 'core/base.html' %}
{% load static %}
{% load user_tags %}
{% block title %}Perfil{% endblock %}


{% block css_extra %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.bootstrap4.min.css" rel="stylesheet" />
{% endblock %}
{% block content %}

<style>.errorlist{color:red;} label{display:none}</style>


<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">

          <div class="row">
            <!-- Formulario -->
            <div class="col-md-10">

                 {% if 'ok' in request.GET %}
                        <p style="color:green;">
                          Guardia Cargada correctamente...
                        </p>
                      {% endif %}

                {% if form.fecha_fin.errors %}
                    <p style="color:red">{{form.fecha_fin.errors}}</p>
                  {% endif %}
              <h3 class="text-center">Regitra las guardias de la Región {{request.user.userregion.region.name}}</h3>
                    <form id = "formulario" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-floating mt-4">
                          <select class="form-control my-3 select2" id="id_name"  name="name" aria-label="Floating label select example">

                              <option selected>Seleccione un Recurso</option>
                               {% for item in profiles %}

                                 <option value="{{item.id}}"  >{{item.name}}</option>
                               {% endfor %}
                          </select>
                        </div>

                     <div class="form-floating my-3">
                        <select class="form-control select2"  id="id_guardia"  name="guardia" aria-label="Floating label select example" multiple>
                            {% for guardia in  guardias %}
                               <option value="{{guardia.id}}"  >{{guardia.name}}</option>
                              {% endfor %}
                        </select>
                      </div>




                        {{form.fecha_inicio}}
                        {{form.fecha_fin}}




                    <p class="mt-3">
                Quieres ver las guadias Cargadas <a  class="link-primary" href="{% url 'core:guardias_especialistas_list' %}">aquí</a>.<br>
                Calendario  <a  class="link-primary" href="{% url 'core:calendario'  %}">aquí</a>.<br>
                         Home  <a  class="link-primary" href="{% url 'core:home'  %}">aquí</a>.<br>

              </p>
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Registrar">
            </div>

          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock %}

 {% block js_extra %}

 <script>

$(document).ready(function () {
        $('.select2').select2({
                theme: "bootstrap4",
                language: 'es',
                allowCLear:true
            });

        $('#id_name').select2({
            allowCLear:true,
            placeholder:"Seleccione una Guardia",
            languaje: "es",
            ajax: {
                url: '{% url 'core:guardiaSemanal_create' %}',
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.name};
                        })
                    };
                }
            },
            minimumInputLength: 1
        });


    });





</script>
<script>



</script>


{% endblock %}

onCall/core/templates/core/guardia_Semanal.html
{% extends 'core/base.html' %}
{% load static %}
{% load user_tags %}
{% block title %}Perfil{% endblock %}


{% block css_extra %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.bootstrap4.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}
{% block content %}

<style>.errorlist{color:red;} label{display:none}</style>


<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">

          <div class="row">
            <!-- Formulario -->
            <div class="col-md-10">

                 {% if 'ok' in request.GET %}
                        <p style="color:green;">
                          Guardia Cargada correctamente...
                        </p>
                      {% endif %}

                {% if form.fecha_fin.errors %}
                    <p style="color:red">{{form.fecha_fin.errors}}</p>
                  {% endif %}
              <h3 class="text-center">Regitra las guardias</h3>
                    <form id = "formulario" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-floating mt-4">
                          <select class="form-control my-3" id="id_name"  name="name" aria-label="Floating label select example">
                            <option selected>Selecione...</option>
                               {% for item in profiles %}
                                 <option value="{{item.id}}"  >{{item.name}}</option>
                               {% endfor %}
                          </select>
                        </div>

                     <div class="form-floating my-3">
                        <select class="form-control"  id="id_guardia"  name="guardia" aria-label="Floating label select example" multiple>

                        </select>
                      </div>




                        {{form.fecha_inicio}}
                        {{form.fecha_fin}}




                    <p class="mt-3">
                Quieres ver las guadias Cargadas <a  class="link-primary" href="{% url 'core:guardias_especialistas_list' %}">aquí</a>.<br>
                Calendario  <a  class="link-primary" href="{% url 'core:calendario'  %}">aquí</a>.<br>
                         Home  <a  class="link-primary" href="{% url 'core:home'  %}">aquí</a>.<br>

              </p>
              <input type="submit"  class="btn btn-primary btn-block mt-3" value="Registrar">
            </div>

          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock %}

 {% block js_extra %}
<script type="text/javascript">
$(document).ready(function () {
     $('#id_name').select2({
        placeholder: "Seleccione un nombre",
        allowClear:true,
        language: 'es'

     });
   $('select[name="name"]').on('change', function () {
      var id = $(this).val();


                if (id === '') {
                    select_products.html(options);
                    return false;
                }
           $.ajax({
                    url: window.location.pathname,
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        'action': 'profile',
                        'id': id
                    },
                    success:function(response){


                      valores_select(response)
                    },

                    error:function(response){
                         console.log("ERROR")
                    }
            });

           function valores_select(data){
                let selec_opcion = document.getElementById("id_guardia");
                selec_opcion.innerHTML = "";
                data.map(
                    (name)=> {
                    if( name.id >0){
                        let option = document.createElement('option');
                           option.value =name.id;
                           option.text =name.name;
                           selec_opcion.appendChild(option);

                            };
                    }
                )
           }
   });
 });


</script>

<script>
    // This code activates flatpickr on fields with the 'datetimefield' class when the document has loaded
    window.addEventListener("DOMContentLoaded", function () {
        flatpickr("#id_fecha_inicio", {
            enableTime: true,
            enableSeconds: true,
            dateFormat: "Y-m-d H:i:S",
        });
    });
</script>

<script>
    // This code activates flatpickr on fields with the 'datetimefield' class when the document has loaded
    window.addEventListener("DOMContentLoaded", function () {
        flatpickr("#id_fecha_fin", {
            enableTime: true,
            enableSeconds: true,
            dateFormat: "Y-m-d H:i:S",
        });
    });
</script>

{% endblock %}

onCall/core/templates/core/guardias_especialidades_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar Guardia{% endblock %}
{% block content %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
          <form action="" method="post">{% csrf_token %}
            <p>¿Estás seguro de que quieres borrar la Guardia de <b>"{{ object.name }}"</b> con fecha de inicio <b>"{{ object.fecha_inicio }}"</b> y fin <b>"{{ object.fecha_fin }}"</b> ?</p>
            <input type="submit" class="btn btn-primary btn-block" value="Sí, borrar la guardia" />
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

onCall/core/templates/core/guardias_especialidades_update.html
{% extends 'core/base.html' %}
{% block title %}Editar Guardia{% endblock %}
{% load static %}
{% block css_extra %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.bootstrap4.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

{% endblock %}

{% block content %}

<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
         <a href="{% url 'core:guardias_especialistas_list'  %}" class="text-muted">
                       <i class="bi bi-backspace-fill"></i> Regresar
               </a>
        <div>
          {% if 'ok' in request.GET %}
            <p style="color:green;">
              Guardia editada correctamente.
              <a style="color:black;" href="{% url 'core:guardias_especialistas_list' %}">Haz clic aquí para ver el resultado</a>.
            </p>
          {% endif %}
          <form class="mt-3" action="" method="post">{% csrf_token %}

            {{ form.as_p }}

          <div class="text-center">
            <input type="submit" class="btn btn-primary btn-block" value="Actualizar" />
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</main>



{% endblock %}

{% block js_extra %}

<script type="text/javascript">
$(document).ready(function () {
    $('#id_guardia').select2({
        placeholder: "Seleccione una Guardia",
        allowClear:true,
        language: 'es'

     });

     $('#id_name').select2({
        placeholder: "Seleccione un nombre",
        language: 'es'

     });



 });
</script>

<script>
    // This code activates flatpickr on fields with the 'datetimefield' class when the document has loaded
    window.addEventListener("DOMContentLoaded", function () {
        flatpickr("#id_fecha_inicio", {
            enableTime: true,
            enableSeconds: true,
            dateFormat: "Y-m-d H:i:S",
        });
    });
</script>

<script>
    // This code activates flatpickr on fields with the 'datetimefield' class when the document has loaded
    window.addEventListener("DOMContentLoaded", function () {
        flatpickr("#id_fecha_fin", {
            enableTime: true,
            enableSeconds: true,
            dateFormat: "Y-m-d H:i:S",
        });
    });
</script>
{% endblock %}